version: "3"

secrets:
  tls_certificate:
    file: ${TLS_CERT}
  tls_certificate_key:
    file: ${TLS_CERT_KEY}

services:
  app:
    container_name: app
    image: dkitsu
    build: .
    ports: 
      - '80:80'
      - '443:443'
    environment:
      - TLS_CERT=/run/secrets/cert.pem
      - TLS_CERT_KEY=/run/secrets/cert-key.pem
    secrets:
      - source: tls_certificate
        target: cert.pem
      - source: tls_certificate_key
        target: cert-key.pem
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    expose: 
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=dkitsu
    restart: always
