networks:
  vnet:
    external: true

services:
  web:
    container_name: casemanager
    image: casemanager:latest
    build: .
    environment:
      - 'HOST=0.0.0.0'
      - 'PORT=3000'
      - 'ADMIN_EMAIL="alice@jeremymeadows.dev"'
      - 'ADMIN_USERNAME="Alice"'
      - 'ADMIN_PASSWORD="passw0rd"'
      - 'SPLASH_MESSAGE="Sign in to the demo app with the credentials `$ADMIN_EMAIL` and `$ADMIN_PASSWORD`."'
      - 'DEMO_MODE="true"'
    networks:
      - vnet
    volumes:
      - type: bind
        source: ./db.sqlite
        target: /app/db.sqlite
    expose:
      - 3000
    restart: always